[package]
name = "dmacs"
version = "0.1.0"
edition = "2024"

[dependencies]
isatty = "0.1"
libc = "0.2.153"
log = "0.4"
pancurses = "0.17.0"
simplelog = "0.12.2"

[dev-dependencies]
tempfile = "3.10.1"

[[bin]]
name = "dmacs"
path = "src/bin/dmacs.rs"

[lib]
name = "dmacs"
path = "src/lib.rs"