[package]
name = "dmacs"
version = "0.1.0"
edition = "2024"

[dependencies]
crossterm = "0.27.0"
isatty = "0.1.0"
libc = "0.2.153"

[[bin]]
name = "dmacs"
path = "src/bin/dmacs.rs"

[lib]
name = "dmacs"
path = "src/lib.rs"